- name: Install Nginx
  hosts: all
  tasks:
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: installed

- name: Download and Extract Frontend
  get_url:
    url: curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"


















    # Let's download the HTDOCS content and deploy under the Nginx path.
    # curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"